/* gaultb.com — access-code table (generated by tools/add-code.py; edit with that tool).
 *
 * No plain codes or share links live here:
 *   hash = SHA-256(salt + code)               -> identifies an entry
 *   ct   = AES-256-GCM(share URL), key = PBKDF2-SHA256(code, kdfSalt, iterations)
 * Honest caveat: a 4-digit code has only 10,000 possibilities, so this hides links
 * from casual reading; the real protection is the Nextcloud share password.
 *
 * DEMO: an entry whose "note" starts with "DEMO" is a demonstration only; it points at
 *       the placeholder https://files.gaultb.com/login, not a real share. Remove it
 *       before going live (see README.md).
 */
window.GAULTB_CONFIG = /*BEGIN-CONFIG*/{
  "version": 1,
  "salt": "9def94597a42c7d315d746a7561664b7",
  "kdf": {
    "name": "PBKDF2",
    "hash": "SHA-256",
    "iterations": 600000
  },
  "allowedHosts": [
    "files.gaultb.com"
  ],
  "entries": [
    {
      "hash": "f2954cac770ad657c9cc61f9e9bd81be09c5f2c8acf90e9311eae1b84b2f9865",
      "kdfSalt": "0+jW4Cx2PeHSdmeAZCsG3A==",
      "iv": "ZhYqaATQyPuvE8S9",
      "ct": "pQM+3086PUe1LTi/VCbUYcOQg+uPvfxeRxAOZb2pbNmjmCZzmZH60bHSnaTqeQ==",
      "note": "Admin sign-in"
    }
  ]
}/*END-CONFIG*/;
