/* gaultb.com — access-code table (generated by tools/add-code.py; edit with that tool).
 *
 * No plain codes or share links live here:
 *   hash = SHA-256(salt + code)               -> identifies an entry
 *   ct   = AES-256-GCM(share URL), key = PBKDF2-SHA256(code, kdfSalt, iterations)
 * Honest caveat: a 4-digit code has only 10,000 possibilities, so this hides links
 * from casual reading; the real protection is the Nextcloud share password.
 *
 * DEMO: an entry whose "note" starts with "DEMO" is a demonstration only; it points at
 *       the placeholder https://files.gaultb.com/login, not a real share. Remove it
 *       before going live (see README.md).
 */
window.GAULTB_CONFIG = /*BEGIN-CONFIG*/{
  "version": 1,
  "salt": "9def94597a42c7d315d746a7561664b7",
  "kdf": {
    "name": "PBKDF2",
    "hash": "SHA-256",
    "iterations": 600000
  },
  "allowedHosts": [
    "files.gaultb.com"
  ],
  "entries": [
    {
      "hash": "f2954cac770ad657c9cc61f9e9bd81be09c5f2c8acf90e9311eae1b84b2f9865",
      "kdfSalt": "weOm04VqwWOBgH01AlnTKw==",
      "iv": "2t/Rprmejz9KaKPH",
      "ct": "S91gJSdMoKWimoupkcIh3VE8pgMgospCjfmW7g1FnJGzmD1hGLexcIG8DBHQdrRidZ8o1jgdskVY",
      "note": "William admin sign-in (Librecloud)"
    },
    {
      "hash": "7174915f4d268ee4164a49ca945b2ecdc1c568f73cc0ccecd78f1608bdf0edd8",
      "kdfSalt": "djBiWQfNNhHGylMbtLklwg==",
      "iv": "6kNXCDlCttPWfLGR",
      "ct": "4jR0JQb+5GR59WPvfR+o9jfACdXyz53A3p7fqP+s8BVTmisJ5C9RrPT3qsBju0bnMgTiYHw08Nfb8A==",
      "note": "Vera Cohen view-only share"
    },
    {
      "hash": "20688ae450602b716ab91b4d7131076f2b6c941913df74a043ffb7636af963b6",
      "kdfSalt": "KTV/Fb0xDYHAw26PBKWTQQ==",
      "iv": "RF29LBZg7ZfJAEQq",
      "ct": "G+v3NlFUK6utaRffKkmDKfzeKYJBcdJUo2L9E/LgzCUfkhUkU0lLyJ8JznUqcFK5I8GF8yyqgjy/IA==",
      "note": "Tom view/download/upload share"
    }
  ]
}/*END-CONFIG*/;
